// Fact flashcards: C(chapter, front, back). Service-identification cards are generated from the decoder.
C("concepts", "What are the five characteristics of cloud computing?", "On-demand self-service, broad network access, multi-tenancy and resource pooling, rapid elasticity and scalability, measured service.");
C("concepts", "Name the six advantages of cloud computing.", "Trade CAPEX for OPEX, economies of scale, stop guessing capacity, speed and agility, stop running data centers, go global in minutes.");
C("concepts", "In IaaS, which layers does the customer manage?", "The operating system and everything above it: middleware, runtime, data and applications.");
C("concepts", "Give one AWS example each of IaaS, PaaS and SaaS.", "IaaS: EC2. PaaS: Elastic Beanstalk. SaaS: a finished service such as Rekognition (or Gmail outside AWS).");
C("concepts", "What three things do you pay for in AWS's pay-as-you-go model?", "Compute time, data stored, and data transferred out. Data transferred in is free.");
C("concepts", "Elasticity vs agility?", "Elasticity: resources scale out and in automatically with demand. Agility: you get new resources in minutes instead of weeks.");
C("concepts", "Vertical vs horizontal scaling?", "Vertical: a bigger instance (scale up). Horizontal: more instances (scale out).");
C("concepts", "What is the minimum for high availability on AWS?", "Running across at least two Availability Zones.");
C("concepts", "What does BYOL mean?", "Bring your own license: reuse software licenses you already own on AWS, often with Dedicated Hosts.");
C("wa", "Name the six Well-Architected pillars.", "Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, Sustainability.");
C("wa", "Which pillar includes “operations as code” and “small, reversible changes”?", "Operational Excellence.");
C("wa", "Which pillar includes “automatically recover from failure” and “test recovery procedures”?", "Reliability.");
C("wa", "Which pillar includes “go global in minutes” and “use serverless architectures”?", "Performance Efficiency.");
C("wa", "Which pillar includes “analyze and attribute expenditure”?", "Cost Optimization (for example with cost allocation tags).");
C("wa", "Which pillar includes “maximize utilization” to reduce environmental impact?", "Sustainability.");
C("wa", "What is a game day?", "A planned simulation of a real event (such as a traffic spike or failure) to test systems and teams.");
C("caf", "Name the six AWS CAF perspectives.", "Business, People, Governance (business side); Platform, Security, Operations (technical side).");
C("caf", "What are the four AWS CAF transformation phases, in order?", "Envision, Align, Launch, Scale.");
C("caf", "Name the 7 Rs of migration.", "Retire, Retain, Relocate, Rehost, Replatform, Repurchase, Refactor.");
C("caf", "Rehost vs replatform?", "Rehost moves the app as it is (lift and shift). Replatform makes a few cloud optimizations, such as moving to RDS (lift and reshape).");
C("caf", "What is repurchase?", "Replacing an application with a different product, usually SaaS (drop and shop).");
C("srm", "AWS is responsible for security ___ the cloud; the customer for security ___ the cloud.", "OF the cloud (AWS); IN the cloud (customer).");
C("srm", "Name the three shared controls.", "Patch management, configuration management, awareness and training.");
C("srm", "Who patches the guest OS on EC2? Who patches the OS under RDS?", "EC2: the customer. RDS: AWS.");
C("srm", "Is your workload automatically PCI compliant because AWS is?", "No. AWS's certifications cover the infrastructure; you must make your own workload compliant.");
C("iam", "What can an IAM group contain?", "Only IAM users. Groups can't contain other groups.");
C("iam", "In IAM policy evaluation, what wins between an Allow and an explicit Deny?", "The explicit Deny always wins.");
C("iam", "What protects console access, and what protects CLI/SDK access?", "Console: password + MFA. CLI and SDK: access keys.");
C("iam", "Credentials Report vs Access Advisor?", "Credentials Report: account-wide status of every user's credentials. Access Advisor: one user's permitted services and when each was last used.");
C("iam", "Name four root-only tasks.", "Change account name or root email, close the account, register as an RI Marketplace seller, enable S3 MFA Delete (also restore IAM permissions, sign up for GovCloud).");
C("iam", "Cognito vs IAM Identity Center?", "Cognito: your app's customers. IAM Identity Center: your employees' single sign-on to AWS accounts and apps.");
C("netsec", "Security group vs NACL: state and rules?", "Security group: stateful, allow rules only, instance level. NACL: stateless, allow and deny, subnet level.");
C("netsec", "Default security group behavior?", "All inbound traffic blocked; all outbound traffic allowed.");
C("netsec", "Where can AWS WAF be deployed?", "On Application Load Balancers, API Gateway and CloudFront (not on NLB or directly on EC2).");
C("netsec", "Name three activities prohibited in penetration testing.", "DoS/DDoS (including simulated), port, protocol or request flooding, and DNS zone walking on Route 53 hosted zones.");
C("crypto", "KMS vs CloudHSM?", "KMS: shared, fully managed key service. CloudHSM: dedicated hardware, you manage the keys (FIPS 140-2 Level 3).");
C("crypto", "Secrets Manager vs Parameter Store?", "Both store secrets. Secrets Manager rotates them automatically (paid). Parameter Store is free (standard) without automatic rotation.");
C("crypto", "Which services encrypt data by default?", "CloudTrail logs, S3 Glacier classes, Storage Gateway, and every new S3 object (since 2023).");
C("detect", "CloudTrail vs Config vs CloudWatch?", "CloudTrail: who made which API call. Config: resource configuration over time and compliance. CloudWatch: performance metrics, logs and alarms.");
C("detect", "GuardDuty vs Inspector?", "GuardDuty: detects threats from logs (behavior). Inspector: scans software for vulnerabilities (CVEs).");
C("infra", "Name the four factors for choosing a Region.", "Compliance and data residency, latency to users, service availability, pricing.");
C("infra", "Which AWS services are global?", "IAM, Route 53, CloudFront and WAF (for CloudFront).");
C("infra", "Order the DR strategies from cheapest to fastest.", "Backup and restore, pilot light, warm standby, multi-site active-active.");
C("infra", "RPO vs RTO?", "RPO: how much data you can afford to lose. RTO: how long you can afford to be down.");
C("edge", "Name four Route 53 routing policies and their use.", "Simple (one answer), weighted (split traffic), latency (fastest Region), failover (switch when the primary is unhealthy).");
C("edge", "CloudFront vs Global Accelerator?", "CloudFront caches HTTP content at the edge. Global Accelerator gives 2 static IPs and routes TCP/UDP traffic over the AWS network without caching.");
C("ec2", "Which ports are SSH, RDP, HTTP and HTTPS?", "22, 3389, 80, 443.");
C("ec2", "Order EC2 purchase options from cheapest to most expensive.", "Spot (up to 90% off), Reserved/Savings Plans (up to 72%), On-Demand, Dedicated Host (most expensive).");
C("ec2", "Standard RI vs Convertible RI?", "Standard: bigger discount, fixed family and OS. Convertible: can change family, OS and tenancy, with a smaller discount (up to 66%).");
C("elb", "ALB vs NLB vs GWLB layers?", "ALB: layer 7 (HTTP). NLB: layer 4 (TCP/UDP). GWLB: layer 3 (appliances).");
C("containers", "What are Lambda's maximum run time and memory?", "15 minutes per invocation and up to 10 GB of memory.");
C("containers", "ECS EC2 launch type vs Fargate?", "EC2 launch type: you manage the instances. Fargate: serverless, AWS runs the infrastructure.");
C("storage", "Can an EBS volume move to another AZ directly?", "No. Take a snapshot and create a new volume from it in the other AZ.");
C("storage", "What happens to instance store data when an instance stops?", "It is lost. Instance store is temporary.");
C("storage", "Block, file and object storage on AWS?", "Block: EBS, instance store. File: EFS, FSx. Object: S3.");
C("s3", "What is S3's designed durability?", "99.999999999% (11 nines), the same for every storage class.");
C("transfer", "When should you use Snowball instead of the network?", "When transferring over the network would take more than about a week.");
C("transfer", "DataSync vs Storage Gateway?", "DataSync moves data into AWS (migration or scheduled copies). Storage Gateway lets on-premises apps keep using cloud storage.");
C("db", "Multi-AZ vs read replicas?", "Multi-AZ: a standby for automatic failover (availability). Read replicas: read-only copies to scale reads (performance).");
C("db", "OLTP vs OLAP, and an AWS service for each?", "OLTP (transactions): RDS, Aurora. OLAP (analytics): Redshift.");
C("db", "DAX vs ElastiCache?", "DAX caches only DynamoDB (microseconds). ElastiCache caches any database or sessions.");
C("db", "How is Athena priced?", "Per TB of data each query scans. Compressed, columnar files (such as Parquet) cost less to query.");
C("network", "Is VPC peering transitive?", "No. Each pair of VPCs needs its own peering, or use a Transit Gateway.");
C("network", "Site-to-Site VPN vs Direct Connect?", "VPN: over the internet, encrypted, quick to set up. Direct Connect: private dedicated line, consistent, takes weeks.");
C("integration", "SQS vs SNS?", "SQS: queue, each message processed once by one consumer, stored until processed. SNS: pub/sub, every subscriber gets every message, nothing stored.");
C("integration", "Standard vs FIFO SQS queue?", "Standard: nearly unlimited throughput, best-effort order. FIFO: strict order, exactly-once processing.");
C("monitor", "Which EC2 metric is NOT collected by default?", "Memory (RAM) utilization. Install the CloudWatch agent.");
C("deploy", "CloudFormation vs Elastic Beanstalk?", "CloudFormation builds any infrastructure from templates. Beanstalk runs a standard app environment for your uploaded code.");
C("ml", "Transcribe vs Polly?", "Transcribe: speech to text. Polly: text to speech.");
C("ml", "Textract vs Comprehend?", "Textract extracts text from scanned documents. Comprehend analyzes the meaning of text (sentiment, entities).");
C("pricing", "What are AWS's four pricing principles?", "Pay as you go, save when you commit, pay less by using more, pay less as AWS grows.");
C("pricing", "Compute Savings Plans vs EC2 Instance Savings Plans?", "Compute SP: up to 66% off, any family or Region, also Fargate and Lambda. EC2 Instance SP: up to 72%, one family in one Region.");
C("pricing", "Which data transfer is free?", "Inbound from the internet, and between instances in the same AZ over private IPs.");
C("pricing", "Which services have no charge of their own?", "IAM, VPC, CloudFormation, Elastic Beanstalk, Auto Scaling, Organizations (you pay for the resources they create).");
C("pricing", "What are the three classic AWS Free Tier offer types?", "Always Free, 12 months free, and short free trials. (Since July 2025, new accounts get credits instead of the 12-months-free offers; Always Free still applies.)");
C("accounts", "Do SCPs apply to the management account?", "No. They apply to member accounts, including their root users.");
C("accounts", "Do SCPs grant permissions?", "No. They only limit; users still need IAM policies that allow actions.");
C("accounts", "Three benefits of consolidated billing?", "One bill, combined usage for volume discounts, and shared RI and Savings Plans discounts.");
C("costtools", "Pricing Calculator vs Cost Explorer?", "Pricing Calculator estimates future costs before you build. Cost Explorer analyzes past costs and forecasts.");
C("costtools", "Budgets vs CloudWatch billing alarm?", "Budgets can alert on forecasts and track usage and reservations. A billing alarm watches only actual charges.");
C("costtools", "Name the six Trusted Advisor categories.", "Cost optimization, performance, security, fault tolerance, service limits, operational excellence.");
C("support", "Which classic plan has a designated TAM and 15-minute critical response?", "Enterprise.");
C("support", "Classic support response times for critical issues?", "Developer: <12 business hours (impaired). Business: <1 hour (production down). Enterprise On-Ramp: <30 minutes. Enterprise: <15 minutes.");
C("support", "Cheapest classic plan with 24/7 phone support and full Trusted Advisor?", "Business (in the new lineup, Business Support+).");
C("support", "What does the Concierge Support Team help with?", "Billing and account questions and best practices (Enterprise and Enterprise On-Ramp).");
