// Service decoder: D(name, category, chapter, what it does, cue that points to it). Each cue also becomes a flashcard.
// Compute
D("Amazon EC2", "Compute", "ec2", "Virtual servers you configure and manage (IaaS).", "");
D("EC2 Spot Instances", "Compute", "ec2", "Spare EC2 capacity at up to 90% off that AWS can reclaim with 2 minutes' notice.", "the cheapest compute for jobs that can be interrupted");
D("EC2 Reserved Instances", "Compute", "ec2", "Up to 72% off for a 1- or 3-year commitment to an instance configuration.", "reserve a specific instance type in a Region for 1 or 3 years at a discount");
D("EC2 Dedicated Hosts", "Compute", "ec2", "A whole physical server for you, with socket and core visibility.", "bring your own per-socket or per-core licenses");
D("EC2 Dedicated Instances", "Compute", "ec2", "Instances on hardware not shared with other customers, without host control.", "hardware isolation from other customers, no host control needed");
D("On-Demand Capacity Reservations", "Compute", "ec2", "Reserve EC2 capacity in one AZ for any duration, without a discount.", "guarantee capacity in a specific AZ for a short event");
D("Amazon Machine Image (AMI)", "Compute", "ec2", "A template with the OS and software used to launch instances.", "launch many identical, pre-configured instances quickly");
D("EC2 Image Builder", "Compute", "ec2", "Automates building, testing and distributing AMIs and container images.", "");
D("EC2 User Data", "Compute", "ec2", "A script that runs once at first boot, as root.", "install software automatically when an instance first starts");
D("EC2 Instance Connect", "Compute", "ec2", "Browser-based SSH with temporary keys pushed by AWS (port 22 still open).", "");
D("Elastic IP address", "Networking", "network", "A static public IPv4 address you attach to an instance.", "");
D("AWS Lambda", "Compute", "containers", "Runs code in response to events without servers; up to 15 minutes per run.", "run code on an event with no servers and pay per request");
D("AWS Batch", "Compute", "containers", "Runs large numbers of batch jobs on EC2 or Spot, with no time limit.", "hundreds of thousands of batch jobs with long run times");
D("Amazon Lightsail", "Compute", "containers", "Simple virtual servers, databases and networking at a low fixed monthly price.", "a beginner-friendly server with predictable monthly pricing");
D("AWS Elastic Beanstalk", "Compute", "deploy", "PaaS: upload code and AWS runs the EC2, load balancing and scaling.", "developers just upload code and AWS handles the environment");
D("AWS Outposts", "Compute", "infra", "AWS-managed racks installed in your own data center.", "run AWS services on premises with the same APIs and tools");
D("AWS Local Zones", "Compute", "infra", "AWS compute and storage placed near large cities, extending a Region.", "single-digit millisecond latency near a big city");
D("AWS Wavelength", "Compute", "infra", "AWS compute inside telecom providers' 5G networks.", "ultra-low latency for apps on 5G mobile devices");
D("Amazon EC2 Auto Scaling", "Compute", "elb", "Adds and removes EC2 instances to match demand and replaces unhealthy ones.", "automatically add instances at peak and remove them after");
// Containers
D("Amazon ECS", "Containers", "containers", "AWS's own container orchestration service.", "run Docker containers with an AWS-native orchestrator");
D("Amazon EKS", "Containers", "containers", "Managed Kubernetes.", "a company already uses Kubernetes and wants it managed on AWS");
D("AWS Fargate", "Containers", "containers", "Serverless compute engine for ECS and EKS containers.", "run containers without managing any servers");
D("Amazon ECR", "Containers", "containers", "Private registry for container images.", "store and version private Docker images");
// Storage
D("Amazon S3", "Storage", "s3", "Object storage with 11 nines of durability and no size limit.", "store any amount of objects such as backups, media and data lakes");
D("S3 Intelligent-Tiering", "Storage", "s3", "Moves objects between access tiers automatically; no retrieval fees.", "unknown or changing access patterns with no retrieval fees");
D("S3 Standard-IA", "Storage", "s3", "Lower-cost storage for infrequent access with millisecond retrieval, multi-AZ.", "data read about once a month that must come back in milliseconds");
D("S3 One Zone-IA", "Storage", "s3", "Infrequent-access storage in a single AZ, cheaper than Standard-IA.", "cheap storage for secondary copies you can re-create");
D("S3 Glacier Instant Retrieval", "Storage", "s3", "Archive storage with millisecond retrieval, for data read about once a quarter.", "archive data read about once a quarter that still needs millisecond access");
D("S3 Glacier Flexible Retrieval", "Storage", "s3", "Archive storage with retrieval from minutes to 12 hours; free bulk retrieval.", "archives you may need back within minutes to a few hours, once or twice a year");
D("S3 Glacier Deep Archive", "Storage", "s3", "The lowest-cost storage; retrieval in 12 to 48 hours; 180-day minimum.", "keep records for years at the lowest possible cost");
D("S3 Express One Zone", "Storage", "s3", "Single-AZ, highest-performance S3 class with single-digit ms latency.", "");
D("S3 Lifecycle rules", "Storage", "s3", "Automatically move objects to cheaper classes or delete them after a time.", "move objects to cheaper storage automatically after 30 or 90 days");
D("S3 Versioning", "Storage", "s3", "Keeps every version of each object.", "recover from accidental overwrites or deletes");
D("S3 Object Lock", "Storage", "s3", "WORM protection that prevents deletion until a retention date.", "records nobody can delete or change for years (WORM)");
D("S3 Cross-Region Replication", "Storage", "s3", "Asynchronously copies objects to a bucket in another Region.", "keep a copy of S3 data in another Region for compliance or latency");
D("S3 Transfer Acceleration", "Storage", "s3", "Speeds up long-distance uploads through edge locations.", "faster uploads from far away into a single bucket");
D("S3 Block Public Access", "Storage", "s3", "Account- or bucket-level setting that prevents public access.", "make sure no bucket in the account can ever become public");
D("S3 pre-signed URL", "Storage", "s3", "A temporary URL that grants access to one private object.", "");
D("Amazon EBS", "Storage", "storage", "Block storage volumes attached to one EC2 instance in one AZ.", "a persistent disk for one instance, such as a boot or database volume");
D("EC2 instance store", "Storage", "storage", "Physical disk on the host with the highest I/O, but temporary.", "the fastest disk for temporary cache or scratch data");
D("EBS Snapshot Archive", "Storage", "storage", "An archive tier for EBS snapshots, 75% cheaper, 24–72 h to restore.", "");
D("Recycle Bin", "Storage", "storage", "Retention rules that let you recover deleted EBS snapshots and AMIs.", "");
D("Amazon EFS", "Storage", "storage", "Managed NFS file system shared by many Linux instances across AZs.", "a shared file system for hundreds of Linux instances");
D("EFS Infrequent Access", "Storage", "storage", "Lower-cost EFS class for files not used often, via lifecycle policies.", "");
D("Amazon FSx for Windows File Server", "Storage", "storage", "Managed Windows file shares with SMB, NTFS and Active Directory.", "a Windows file share with SMB and Active Directory");
D("Amazon FSx for Lustre", "Storage", "storage", "High-performance file system for HPC and ML, integrated with S3.", "a very fast file system for HPC or machine learning");
D("AWS Storage Gateway", "Storage", "transfer", "Hybrid bridge giving on-premises apps access to S3-backed file, volume or tape storage.", "on-premises applications keep using cloud storage every day");
D("Tape Gateway", "Storage", "transfer", "A Storage Gateway mode that replaces physical backup tapes with virtual tapes.", "replace physical tape backups without changing backup software");
D("AWS Backup", "Storage", "transfer", "Central, policy-based backups across AWS services, Regions and accounts.", "one place to manage backups for EBS, RDS, DynamoDB, EFS and more");
D("AWS Elastic Disaster Recovery", "Storage", "transfer", "Continuous replication of servers into AWS with failover in minutes.", "recover on-premises servers into AWS within minutes");
// Migration and transfer
D("AWS Snowball Edge", "Migration and transfer", "transfer", "Rugged device to move terabytes to petabytes offline or compute at the edge.", "move huge data when the network would take more than a week");
D("AWS DataSync", "Migration and transfer", "transfer", "Online, scheduled, incremental transfer to S3, EFS or FSx.", "copy large file data online to AWS on a schedule");
D("AWS Transfer Family", "Migration and transfer", "transfer", "Managed SFTP, FTPS and FTP endpoints backed by S3 or EFS.", "partners must upload files over SFTP into S3");
D("AWS Application Migration Service", "Migration and transfer", "caf", "Lift-and-shift migration of servers into AWS with continuous replication.", "rehost servers into AWS with minimal changes");
D("AWS Database Migration Service", "Migration and transfer", "caf", "Migrates databases while the source stays online, same or different engines.", "migrate a database with minimal downtime");
D("AWS Application Discovery Service", "Migration and transfer", "caf", "Collects on-premises server data and dependencies for migration planning.", "inventory on-premises servers and dependencies before a migration");
D("Migration Evaluator", "Migration and transfer", "caf", "Builds a data-driven business case for moving to AWS.", "estimate what the current environment would cost on AWS");
D("AWS Migration Hub", "Migration and transfer", "caf", "Tracks migration progress across tools in one place.", "");
// Databases
D("Amazon RDS", "Database", "db", "Managed relational databases: MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, Db2.", "a managed MySQL, PostgreSQL, Oracle or SQL Server database");
D("RDS Multi-AZ", "Database", "db", "A standby database in another AZ with automatic failover.", "a database that fails over automatically if an AZ fails");
D("RDS read replicas", "Database", "db", "Up to 15 read-only copies to scale read traffic.", "offload read-heavy or reporting queries from the primary database");
D("Amazon Aurora", "Database", "db", "AWS's MySQL/PostgreSQL-compatible engine, faster, with storage across 3 AZs.", "MySQL or PostgreSQL compatible with higher performance");
D("Aurora Serverless", "Database", "db", "Aurora that scales capacity automatically with usage.", "a relational database for intermittent, unpredictable use");
D("Amazon DynamoDB", "Database", "db", "Serverless key-value NoSQL with single-digit millisecond latency at any scale.", "serverless key-value NoSQL at massive scale");
D("DynamoDB Accelerator (DAX)", "Database", "db", "In-memory cache for DynamoDB with microsecond reads.", "microsecond reads for DynamoDB");
D("DynamoDB global tables", "Database", "db", "Multi-Region, active-active replication of DynamoDB tables.", "read and write the same NoSQL data in several Regions");
D("Amazon ElastiCache", "Database", "db", "Managed in-memory caching with Redis/Valkey or Memcached.", "cache frequent queries and sessions in memory");
D("Amazon MemoryDB", "Database", "db", "Durable, Redis-compatible in-memory database.", "");
D("Amazon DocumentDB", "Database", "db", "Managed document database, MongoDB-compatible.", "a MongoDB-compatible managed database");
D("Amazon Neptune", "Database", "db", "Managed graph database.", "highly connected data such as social networks and fraud rings");
D("Amazon Timestream", "Database", "db", "Time-series database.", "store and analyze sensor readings over time");
D("Amazon Keyspaces", "Database", "db", "Managed Apache Cassandra-compatible database.", "");
D("Amazon Managed Blockchain", "Database", "other", "Create and manage blockchain networks (Hyperledger Fabric, Ethereum).", "");
// Analytics
D("Amazon Redshift", "Analytics", "db", "Columnar data warehouse for OLAP analytics at petabyte scale.", "a data warehouse for analytics and BI");
D("Amazon Athena", "Analytics", "db", "Serverless SQL queries directly on files in S3; pay per TB scanned.", "query files in S3 with SQL and no servers");
D("Amazon EMR", "Analytics", "db", "Managed Hadoop and Spark clusters for big data.", "process big data with Hadoop or Spark");
D("AWS Glue", "Analytics", "db", "Serverless ETL and a data catalog.", "extract, transform and load data for analytics");
D("Amazon QuickSight", "Analytics", "db", "Serverless business intelligence dashboards.", "interactive dashboards for business users");
D("Amazon OpenSearch Service", "Analytics", "db", "Managed search and log analytics (successor to Elasticsearch on AWS).", "full-text search and log analytics");
D("Amazon Kinesis Data Streams", "Analytics", "integration", "Real-time ingestion of streaming data at massive scale.", "real-time streaming data such as clickstreams and IoT");
D("Amazon Data Firehose", "Analytics", "integration", "Loads streaming data into S3, Redshift or OpenSearch, fully managed.", "");
// Networking and content delivery
D("Amazon VPC", "Networking", "network", "Your private network in a Region, split into subnets per AZ.", "");
D("Internet gateway", "Networking", "network", "Connects a VPC to the internet.", "make a subnet reachable from the internet");
D("NAT gateway", "Networking", "network", "Lets private subnets reach the internet outbound only.", "private instances need to download updates");
D("Network ACL", "Networking", "network", "Stateless subnet firewall with allow and deny rules.", "deny a specific IP address at the subnet level");
D("Security group", "Networking", "netsec", "Stateful instance firewall with allow rules only.", "an instance-level firewall that allows specific ports");
D("VPC Flow Logs", "Networking", "network", "Records IP traffic in a VPC, subnet or network interface.", "troubleshoot connectivity by recording IP traffic");
D("VPC peering", "Networking", "network", "Private connection between two VPCs; not transitive.", "");
D("VPC endpoints", "Networking", "network", "Private access from a VPC to AWS services without the internet.", "reach S3 or DynamoDB without going over the internet");
D("AWS PrivateLink", "Networking", "network", "Expose a service privately to many VPCs through interface endpoints.", "");
D("AWS Transit Gateway", "Networking", "network", "Hub that connects many VPCs and on-premises networks.", "connect dozens of VPCs through one central hub");
D("AWS Site-to-Site VPN", "Networking", "network", "Encrypted tunnel between your network and AWS over the internet.", "a quick, encrypted connection to on premises over the internet");
D("AWS Direct Connect", "Networking", "network", "Dedicated private physical connection to AWS.", "a private, consistent, high-bandwidth line to AWS");
D("AWS Client VPN", "Networking", "network", "Managed VPN for individual users' devices.", "");
D("Amazon Route 53", "Networking", "edge", "Managed DNS, domain registration, health checks and routing policies.", "DNS, domain names and routing users to healthy endpoints");
D("Amazon CloudFront", "Networking", "edge", "Content delivery network that caches content at edge locations.", "cache content close to users worldwide");
D("AWS Global Accelerator", "Networking", "edge", "Two static anycast IPs that route traffic over the AWS network; no caching.", "static IPs and fast failover for TCP or UDP apps");
D("Elastic Load Balancing", "Networking", "elb", "Spreads traffic across targets in multiple AZs with health checks.", "");
D("Application Load Balancer", "Networking", "elb", "Layer 7 load balancer with path- and host-based routing.", "route HTTP traffic by URL path");
D("Network Load Balancer", "Networking", "elb", "Layer 4 load balancer for TCP/UDP with ultra-low latency and static IPs.", "millions of TCP or UDP requests per second");
D("Gateway Load Balancer", "Networking", "elb", "Layer 3 load balancer that sends traffic through security appliances.", "route traffic through third-party firewall appliances");
D("Amazon API Gateway", "Networking", "containers", "Create, publish and secure REST and WebSocket APIs.", "a managed REST API in front of Lambda");
// Security, identity and compliance
D("AWS IAM", "Security", "iam", "Users, groups, roles and policies that control access to AWS.", "");
D("IAM roles", "Security", "iam", "Temporary permissions that services or users assume.", "give an EC2 application access to S3 without stored keys");
D("IAM Credentials Report", "Security", "iam", "Account-wide report of every user's credential status.", "list all users and whether they use MFA and access keys");
D("IAM Access Advisor", "Security", "iam", "Shows which services a user can access and when they were last used.", "find and remove permissions a user never uses");
D("IAM Access Analyzer", "Security", "detect", "Finds resources shared outside your account or organization.", "find S3 buckets or roles shared with external accounts");
D("AWS IAM Identity Center", "Security", "iam", "Single sign-on to many AWS accounts and business apps.", "employees sign in once to all AWS accounts and apps");
D("Amazon Cognito", "Security", "iam", "Sign-up and sign-in for web and mobile app users, including social login.", "millions of app users with Google or Facebook login");
D("AWS STS", "Security", "iam", "Issues temporary, limited-privilege credentials.", "temporary credentials when assuming a role");
D("AWS Directory Service", "Security", "iam", "Managed Microsoft Active Directory, AD Connector or Simple AD.", "Microsoft Active Directory in AWS or connected to on premises");
D("AWS KMS", "Security", "crypto", "Creates and manages encryption keys used by AWS services.", "manage encryption keys for data at rest");
D("AWS CloudHSM", "Security", "crypto", "Dedicated hardware security modules where you control the keys.", "FIPS-validated dedicated hardware with keys only you control");
D("AWS Certificate Manager", "Security", "crypto", "Free public SSL/TLS certificates with automatic renewal.", "a free TLS certificate for HTTPS on a load balancer");
D("AWS Secrets Manager", "Security", "crypto", "Stores secrets and rotates them automatically.", "automatically rotate database passwords");
D("SSM Parameter Store", "Security", "crypto", "Stores configuration values and secrets, optionally encrypted.", "store configuration values centrally at low cost");
D("AWS Shield Standard", "Security", "netsec", "Free, automatic protection against common DDoS attacks.", "free, always-on DDoS protection");
D("AWS Shield Advanced", "Security", "netsec", "Paid DDoS protection with a 24/7 response team and cost protection.", "DDoS response team and protection from DDoS-related charges");
D("AWS WAF", "Security", "netsec", "Layer 7 web application firewall for ALB, API Gateway and CloudFront.", "block SQL injection and cross-site scripting");
D("AWS Network Firewall", "Security", "netsec", "Managed firewall for an entire VPC, layers 3 to 7.", "filter all traffic entering and leaving a VPC");
D("AWS Firewall Manager", "Security", "netsec", "Central management of firewall rules across an organization.", "apply WAF and security group rules across all accounts");
D("Amazon GuardDuty", "Security", "detect", "Threat detection using ML on CloudTrail, VPC Flow Logs and DNS logs.", "detect compromised instances or crypto mining");
D("Amazon Inspector", "Security", "detect", "Automated vulnerability scanning of EC2, ECR images and Lambda.", "scan instances and container images for CVEs");
D("Amazon Macie", "Security", "detect", "Discovers sensitive data such as PII in S3.", "find PII or sensitive data in S3 buckets");
D("AWS Security Hub", "Security", "detect", "Central view of security findings and best-practice checks across accounts.", "one dashboard of security findings from many services");
D("Amazon Detective", "Security", "detect", "Investigates the root cause of security findings with graphs.", "investigate the root cause of a GuardDuty finding");
D("AWS Artifact", "Security", "detect", "Portal for AWS compliance reports and agreements.", "download SOC or PCI reports or accept a HIPAA BAA");
D("AWS Config", "Security", "detect", "Records resource configurations over time and checks them against rules.", "see how a resource's configuration changed and whether it complies");
D("AWS Audit Manager", "Security", "detect", "Collects evidence for audits.", "");
// Management and governance
D("AWS CloudTrail", "Management and governance", "monitor", "Records every API call: who, what, when and from where.", "find out who deleted a resource");
D("Amazon CloudWatch", "Management and governance", "monitor", "Metrics, alarms, logs and dashboards for resources and apps.", "monitor CPU and set an alarm");
D("CloudWatch Logs", "Management and governance", "monitor", "Collects and searches application and system logs.", "");
D("AWS X-Ray", "Management and governance", "monitor", "Traces requests through distributed applications.", "find which microservice is slowing requests down");
D("AWS Health Dashboard", "Management and governance", "monitor", "AWS service status and events that affect your resources.", "see AWS outages or maintenance affecting your resources");
D("Amazon EventBridge", "Management and governance", "integration", "Event bus with rules and schedules that route events to targets.", "react to events or run a function on a schedule");
D("AWS CloudFormation", "Management and governance", "deploy", "Infrastructure as code with JSON or YAML templates.", "create the same infrastructure repeatedly from templates");
D("AWS CDK", "Management and governance", "deploy", "Define infrastructure in programming languages; generates CloudFormation.", "write infrastructure as code in Python or TypeScript");
D("AWS Systems Manager", "Management and governance", "deploy", "Operate EC2 and on-premises fleets: patching, commands, inventory.", "patch and manage servers on AWS and on premises");
D("Systems Manager Session Manager", "Management and governance", "deploy", "Shell access to instances with no SSH keys and no open ports.", "shell access without port 22 or SSH keys");
D("AWS CloudShell", "Management and governance", "deploy", "Browser-based shell with the AWS CLI preinstalled.", "");
D("AWS Organizations", "Management and governance", "accounts", "Manage many accounts with consolidated billing and SCPs.", "one bill and central policies for many accounts");
D("Service control policies (SCPs)", "Management and governance", "accounts", "Guardrails that limit what accounts and OUs can do.", "stop member accounts from using a service or Region");
D("AWS Control Tower", "Management and governance", "accounts", "Automated setup of a governed multi-account landing zone.", "set up a secure multi-account environment with best practices");
D("AWS Service Catalog", "Management and governance", "accounts", "Self-service portal of approved CloudFormation products.", "users can only launch pre-approved configurations");
D("AWS Resource Access Manager", "Management and governance", "accounts", "Share resources like subnets and Transit Gateways across accounts.", "share subnets with other accounts instead of duplicating them");
D("AWS License Manager", "Management and governance", "other", "Tracks software licenses and enforces license rules.", "");
D("AWS Trusted Advisor", "Management and governance", "costtools", "Best-practice checks: cost, performance, security, fault tolerance, limits, operations.", "check the account for idle resources, open ports and limits");
D("AWS Well-Architected Tool", "Management and governance", "wa", "Free reviews of workloads against the six pillars.", "review a workload against the Well-Architected pillars");
D("Service Quotas", "Management and governance", "costtools", "View quotas and request increases.", "request a higher limit for a service");
D("AWS Launch Wizard", "Management and governance", "other", "Guided deployment of third-party apps such as SQL Server and SAP.", "");
// Developer tools
D("AWS CodeCommit", "Developer tools", "deploy", "Private Git repositories.", "private Git repositories on AWS");
D("AWS CodeBuild", "Developer tools", "deploy", "Serverless build service that compiles and tests code.", "compile and test code without build servers");
D("AWS CodeDeploy", "Developer tools", "deploy", "Automates deployments to EC2, Lambda, ECS and on-premises servers.", "deploy new versions to EC2 and on-premises servers");
D("AWS CodePipeline", "Developer tools", "deploy", "Orchestrates CI/CD release pipelines.", "automate build, test and deploy on every change");
D("AWS CodeArtifact", "Developer tools", "deploy", "Managed repository for software packages and dependencies.", "");
D("AWS Infrastructure Composer", "Developer tools", "deploy", "Visual designer for serverless apps that generates CloudFormation.", "");
// Application integration
D("Amazon SQS", "Application integration", "integration", "Message queue to decouple and buffer work.", "decouple components and buffer requests");
D("SQS FIFO queue", "Application integration", "integration", "Queue with strict ordering and exactly-once processing.", "messages must be processed in exact order");
D("Amazon SNS", "Application integration", "integration", "Pub/sub notifications to many subscribers: email, SMS, SQS, Lambda.", "send one message to many subscribers at once");
D("Amazon MQ", "Application integration", "integration", "Managed ActiveMQ and RabbitMQ brokers.", "migrate apps that use AMQP, MQTT or RabbitMQ");
D("AWS Step Functions", "Application integration", "integration", "Serverless visual workflows that coordinate services.", "coordinate several Lambda functions with retries and branches");
D("Amazon SES", "Application integration", "integration", "Send transactional and marketing email at scale.", "send order confirmation emails to customers");
// AI and ML
D("Amazon Rekognition", "AI and ML", "ml", "Image and video analysis: objects, faces, text, unsafe content.", "detect faces or unsafe content in images");
D("Amazon Transcribe", "AI and ML", "ml", "Speech to text.", "turn call recordings into text");
D("Amazon Polly", "AI and ML", "ml", "Text to lifelike speech.", "read text aloud in a natural voice");
D("Amazon Translate", "AI and ML", "ml", "Machine translation between languages.", "translate a website into many languages");
D("Amazon Comprehend", "AI and ML", "ml", "Natural language processing: sentiment, entities, key phrases.", "find the sentiment of customer reviews");
D("Amazon Lex", "AI and ML", "ml", "Build chatbots with speech and language understanding.", "build a conversational chatbot");
D("Amazon Connect", "AI and ML", "ml", "Cloud contact center.", "a cloud call center for customer service");
D("Amazon Textract", "AI and ML", "ml", "Extracts text, forms and tables from scanned documents.", "pull data out of scanned forms and invoices");
D("Amazon Kendra", "AI and ML", "ml", "ML-powered enterprise search with natural-language questions.", "an intelligent search engine for company documents");
D("Amazon Personalize", "AI and ML", "ml", "Real-time personalized recommendations.", "product recommendations for each shopper");
D("Amazon SageMaker AI", "AI and ML", "ml", "Build, train and deploy custom machine learning models.", "build and train your own ML model");
D("Amazon Bedrock", "AI and ML", "ml", "Managed access to foundation models through one API for generative AI.", "build a generative AI app with foundation models");
D("Amazon Q", "AI and ML", "ml", "Generative AI assistant for developers and businesses.", "a generative AI chat assistant for developers and employees");
// End-user computing, front end, IoT, other
D("Amazon WorkSpaces", "End-user computing", "other", "Managed virtual desktops (Desktop as a Service).", "virtual Windows desktops for remote employees");
D("Amazon AppStream 2.0", "End-user computing", "other", "Streams desktop applications to a browser.", "stream one application to a web browser");
D("AWS Amplify", "Front end and mobile", "other", "Build and host full-stack web and mobile apps.", "quickly build and host a full-stack web or mobile app");
D("AWS AppSync", "Front end and mobile", "other", "Managed GraphQL APIs with real-time and offline sync.", "a GraphQL API for a mobile app");
D("AWS Device Farm", "Front end and mobile", "other", "Test apps on real phones, tablets and browsers.", "test a mobile app on real devices");
D("AWS IoT Core", "Internet of Things", "other", "Connect and manage billions of IoT devices securely.", "connect millions of sensors to AWS");
D("AWS IoT Greengrass", "Internet of Things", "other", "Runs AWS logic and ML locally on edge devices.", "");
D("AWS Ground Station", "Other", "other", "Managed antennas to communicate with satellites.", "");
D("AWS Fault Injection Service", "Other", "other", "Chaos engineering experiments that inject failures.", "");
D("Amazon Pinpoint", "Business applications", "other", "Multichannel marketing campaigns.", "");
// Cost management
D("AWS Pricing Calculator", "Cost management", "costtools", "Estimate the cost of an architecture before you build it.", "estimate costs before deploying");
D("AWS Cost Explorer", "Cost management", "costtools", "Visualize, analyze and forecast your costs; Savings Plans recommendations.", "see spending trends over time and a forecast");
D("AWS Budgets", "Cost management", "costtools", "Alerts on actual or forecasted cost, usage and reservations.", "an alert when forecasted spend will exceed a budget");
D("AWS Cost and Usage Report", "Cost management", "costtools", "The most detailed line-item billing data, delivered to S3.", "the most granular billing data for analysis");
D("AWS Cost Anomaly Detection", "Cost management", "costtools", "ML alerts on unusual spending.", "catch unexpected spending spikes automatically");
D("AWS Compute Optimizer", "Cost management", "costtools", "Right-sizing recommendations from real utilization.", "right-size underused EC2 instances and Lambda functions");
D("AWS Billing Conductor", "Cost management", "costtools", "Custom billing groups and rates for resellers or internal team billing.", "");
D("Cost allocation tags", "Cost management", "accounts", "Tags activated in Billing so costs can be grouped by tag.", "break costs down by project or department");
D("Savings Plans", "Cost management", "pricing", "Discount for a $/hour commitment over 1 or 3 years.", "commit to an hourly spend for a discount across compute");
// Support and resources
D("AWS Marketplace", "Support and resources", "support", "Catalog of third-party software billed through AWS.", "buy third-party software on your AWS bill");
D("AWS Partner Network", "Support and resources", "support", "Consulting and technology partners that help customers.", "find a certified partner to help with a migration");
D("AWS Professional Services", "Support and resources", "support", "AWS's own experts for large projects.", "AWS experts to help deliver a large project");
D("AWS Managed Services", "Support and resources", "support", "AWS operates your infrastructure day to day.", "AWS runs our infrastructure operations for us");
D("AWS re:Post", "Support and resources", "support", "Community Q&A reviewed by AWS experts.", "ask the community a technical question");
D("AWS Knowledge Center", "Support and resources", "support", "Articles answering the most common support questions.", "");
D("AWS Trust & Safety (Abuse)", "Support and resources", "netsec", "Handles reports of AWS resources used for abuse.", "report spam or attacks coming from AWS IP addresses");
D("Technical Account Manager", "Support and resources", "support", "A designated AWS advisor included with Enterprise support.", "");
// Added after QA review
D("Amazon MSK", "Application integration", "integration", "Managed Apache Kafka.", "");
D("AWS Data Exchange", "Analytics", "db", "Find and subscribe to third-party data sets in AWS.", "");
D("AWS AppConfig", "Developer tools", "deploy", "Safely change app settings and feature flags at run time.", "");
D("Amazon WorkSpaces Secure Browser", "End-user computing", "other", "A managed, disposable browser for internal websites and SaaS apps.", "");
D("AWS Activate", "Support and resources", "support", "Startup program with credits, support and training.", "");
D("AWS Prescriptive Guidance", "Support and resources", "support", "AWS-written strategies, guides and patterns for migration and modernization.", "");
D("AWS Schema Conversion Tool", "Migration and transfer", "caf", "Converts a database schema and code to a different engine before migration.", "");
D("AWS Health API", "Management and governance", "monitor", "Programmatic access to AWS Health events (Business-level support or higher).", "");
